site:
  title: "Eclipse Semantic Modeling Framework (ESMF)"
  url: https://eclipse-esmf.github.io
  start_page: esmf-documentation::index.adoc
content:
  sources:
     - url: .
       branches: HEAD
       start_path: documentation
     - url: https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model
       branches: HEAD
       tags: ["v2.2.0", "v2.1.0", "v2.0.0"]
       start_path: documentation
     - url: https://github.com/eclipse-esmf/esmf-sdk
       branches: HEAD
       tags: ["v2.10.3","v2.10.2","v2.10.1","v2.10.0","v2.9.10"]
       start_path: documentation/developer-guide
     - url: https://github.com/eclipse-esmf/esmf-aspect-model-editor
       branches: HEAD
       tags: ["v5.6.1","v5.6.0","v5.5.0"]
       start_path: documentation/ame-guide
     - url: https://github.com/eclipse-esmf/esmf-sdk-js-schematics
       branches: HEAD
       tags: ["v2.8.1","v2.8.0","v2.7.0"]
       start_path: documentation/js-sdk-guide
     - url: https://github.com/eclipse-esmf/esmf-sdk-js-aspect-model-loader
       branches: HEAD
       tags: ["v2.3.3"]
       start_path: documentation/js-sdk-aml-guide
     - url: https://github.com/eclipse-esmf/esmf-sdk-py-aspect-model-loader
       branches: HEAD
       tags: ["v2.2.1", "v2.2.0","v2.1.5","v2.1.4","v2.1.3"]
       start_path: documentation/python-sdk-guide
ui:
  bundle:
    url: https://github.com/eclipse-esmf/esmf-antora-ui/releases/download/v1.6.0/esmf-antora-ui-bundle-1.6.0.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
runtime:
  cache_dir: ./.cache/antora
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
asciidoc:
  attributes:
    doctype: book
    sectanchors: true
    idprefix: ''
    idseparator: '-'
    stem: 'asciimath'
    ok: 'icon:check-circle[role="green",size="2x"]'
    nok: 'icon:times-circle[role="red",size="2x"]'
    # The latest specified SAMM version
    meta-model-version: 2.2.0
    meta-model-full-name: Semantic Aspect Meta Model
    meta-model-abbr: SAMM
    samm: urn:samm:org.eclipse.esmf.samm:meta-model:2.2.0#@
    samm-c: urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#@
    samm-e: urn:samm:org.eclipse.esmf.samm:entity:2.2.0#@
    unit: urn:samm:org.eclipse.esmf.samm:unit:2.2.0#@
    # The version of the latest SAMM maven artifact
    aspect-meta-model-version: '2.2.0'
    esmf-sdk-version: '2.10.3'
    esmf-sdk-js-aspect-model-loader-version: '2.3.3'
    esmf-sdk-py-aspect-model-loader-version: '2.2.1'
    example-ns: com.mycompany@

