= Eclipse Semantic Modeling Framework
:page-layout: tiles

Welcome to the documentation of the artifacts of the Eclipse Semantic Modeling Framework (ESMF).

'''

[.tile]
[.icon-spec]
--
[.title]
Semantic Aspect Meta Model (SAMM)

[.text]
The specification defining how to design Aspect Models. Use Aspect Models to describe domain semantics for your assets.

[.link]
xref:samm-specification:ROOT:index.adoc[Specification]
--

[.tile]
[.icon-cli]
--
[.title]
Aspect Model Editor

[.text]
A visual editor for your Aspect Models. Validates your models automatically against the SAMM specification.

[.link]
xref:ame-guide:ROOT:introduction.adoc[Aspect Model Editor]
--

[.tile]
[.icon-cli]
--
[.title]
SAMM Command Line Interface +
(SAMM CLI)

[.text]
A CLI to validate your Aspect Models against SAMM and transform them to documentation and code.

[.link]
xref:esmf-developer-guide:tooling-guide:samm-cli.adoc[SAMM CLI]
--

[.tile]
[.icon-cli]
--
[.title]
Java SDK

[.text]
Helps to build software solutions based on Aspect Models. Implement your own customized aspect services using Java.

[.link]
xref:esmf-developer-guide:tooling-guide:java-aspect-tooling.adoc[Java SDK]
--

[.tile]
[.icon-cli]
--
[.title]
Python SDK

[.text]
Enables software developers to work with Aspect Models in their Python applications.

[.link]
xref:python-sdk-guide:ROOT:index.adoc[Python SDK]
--

[.tile]
[.icon-cli]
--
[.title]
JavaScript SDK

[.text]
Contains several parts – all aimed at creating a graphical user interface (GUI) for your solution, based on Aspect Models.

[.link]
xref:js-sdk-aml-guide:ROOT:index.adoc[JS SDK Aspect Model Loader] +
xref:js-sdk-guide:ROOT:index.adoc[JS SDK Schematics]
--

For a general introduction of the ESMF, please see the
https://projects.eclipse.org/projects/dt.esmf[ESMF project page] or go to https://github.com/eclipse-esmf[github.com/eclipse-esmf] to find all releases and code on Github.
