= Eclipse Semantic Modeling Framework
:page-layout: tiles


Welcome to the documentation of the artifacts of the Eclipse Semantic Modeling Framework (ESMF).

For a general introduction of the ESMF, please see the
https://projects.eclipse.org/projects/dt.esmf[ESMF project page] or go to https://github.com/eclipse-esmf[github.com/eclipse-esmf] to find all releases and code on github.

'''

[.tile]
[.icon-spec]
--
[.title]
Semantic Aspect Meta Model (SAMM)

[.text]
Aspect models defined using the SAMM describe domain semantics.
Find out how they are defined.

[.link]
xref:samm-specification:ROOT:index.adoc[Specification]
--

[.tile]
[.icon-cli]
--
[.title]
SAMM Command Line Interface (SAMM-CLI)

[.text]
Command line interface to work with Aspect Models: Validate and transform models into documentation
and code.

[.link]
xref:esmf-developer-guide:tooling-guide:samm-cli.adoc[SAMM CLI]
--

[.tile]
[.icon-cli]
--
[.title]
Aspect Model Editor

[.text]
The Aspect Model Editor is a visual editor for Aspect Models, which automatically validates the
models against the BAMM Aspect Meta Model version.

[.link]
xref:ame-guide:ROOT:introduction.adoc[Aspect Model Editor]
--

[.tile]
[.icon-cli]
--
[.title]
Java ESMF SDK

[.text]
The ESMF SDK helps you to build solutions, model your Aspect data, implement your own customized
Aspect or want to integrate existing assets and systems within the Java programming language.
[.link]
xref:esmf-developer-guide:tooling-guide:java-aspect-tooling.adoc[Java SDK]
--

[.tile]
[.icon-cli]
--
[.title]
Python ESMF SDK

[.text]
The Python SDK offers functionality which helps software developers to work with Aspect Models in
their Python applications.
[.link]
xref:python-sdk-guide:ROOT:index.adoc[Python SDK]
--

[.tile]
[.icon-cli]
--
[.title]
JS SDK Aspect Model Loader

[.text]
The JS SDK Aspect Model Loader offers functionality which helps software developers to work with Aspect Models 
in their Typescript applications.
[.link]
xref:js-sdk-aml-guide:ROOT:index.adoc[JS SDK Aspect Model Loader]
--

[.tile]
[.icon-cli]
--
[.title]
JS SDK schematics

[.text]
The JS SDK schematics offers functionality which helps software developers to create Angular components 
and generate code based on RDF aspect module object.
[.link]
xref:js-sdk-guide:ROOT:index.adoc[JS SDK schematics]
--
