= Eclipse Semantic Modeling Framework
:page-layout: tiles

Welcome to the documentation of the artifacts of the Eclipse Semantic Modeling Framework (ESMF).

'''

[.tile]
[.icon-spec]
--
[.title]
Semantic Aspect Meta Model (SAMM)

[.text]
Understand SAMM to describe domain semantics for your assets in Aspect Models. SAMM is expressive and fosters reusability.

[.link]
xref:samm-specification:ROOT:index.adoc[Specification]
--

[.tile]
[.icon-cli]
--
[.title]
Aspect Model Editor

[.text]
Create your Aspect Models graphically and learn SAMM on the go. Generate downstream artifacts, such as OpenAPI specs.

[.link]
xref:ame-guide:ROOT:introduction.adoc[Aspect Model Editor]
--

[.tile]
[.icon-cli]
--
[.title]
SAMM Command Line Interface +
(SAMM CLI)

[.text]
A CLI to validate your Aspect Models against SAMM and transform them to documentation and code.

[.link]
xref:esmf-developer-guide:tooling-guide:samm-cli.adoc[SAMM CLI]
--

[.tile]
[.icon-cli]
--
[.title]
Java SDK

[.text]
Helps to build software solutions based on Aspect Models. Implement your own customized aspect services using Java.

[.link]
xref:esmf-developer-guide:tooling-guide:java-aspect-tooling.adoc[Java SDK]
--

[.tile]
[.icon-cli]
--
[.title]
Python SDK

[.text]
Enables software developers to work with Aspect Models in their Python applications.

[.link]
xref:python-sdk-guide:ROOT:index.adoc[Python SDK]
--

[.tile]
[.icon-cli]
--
[.title]
JavaScript SDK

[.text]
Contains several parts – all aimed at creating a graphical user interface (GUI) for your solution, based on Aspect Models.

[.link]
xref:js-sdk-aml-guide:ROOT:index.adoc[JS SDK Aspect Model Loader] +
xref:js-sdk-guide:ROOT:index.adoc[JS SDK Schematics]
--

Refer to the https://projects.eclipse.org/projects/dt.esmf[ESMF project page,window=_blank] at the Eclipse Foundation for a general introduction to the Eclipse Semantic Modeling Framework project. +
For software releases and code, head over to GitHub: https://github.com/eclipse-esmf[github.com/eclipse-esmf,window=_blank]. And for any questions or exchange, https://chat.eclipse.org/#/room/#eclipse-semantic-modeling-framework:matrix.eclipse.org[join the ESMF chat,window=_blank].

&nbsp; +
&nbsp; +
&nbsp;
